DROP TABLE DEPARTMENTS;
DROP TABLE DEPT_EMP;
DROP TABLE DEPT_MANAGER;
DROP TABLE EMPLOYEES;
DROP TABLE TITLES;
DROP TABLE SALARIES;

CREATE TABLE DEPARTMENTS (
	DEPT_NO VARCHAR PRIMARY KEY,
	DEPT_NAME VARCHAR UNIQUE NOT NULL
);

CREATE TABLE DEPT_EMP(
	EMP_NO INT,
	DEPT_NO VARCHAR,
	FROM_DATE DATE,
	TO_DATE DATE
);

CREATE TABLE DEPT_MANAGER(
	DEPT_NO VARCHAR,
	EMP_NO INT,
	FROM_DATE DATE,
	TO_DATE DATE
);

CREATE TABLE EMPLOYEES(
	EMP_NO INT PRIMARY KEY,
	BIRTH_DATE DATE,
	FIRST_NAME VARCHAR,
	LAST_NAME VARCHAR,
	GENDER VARCHAR,
	HIRE_DATE DATE
);

CREATE TABLE TITLES(
	EMP_NO INT,
	TITLE VARCHAR,
	FROM_DATE DATE,
	TO_DATE DATE
);

CREATE TABLE SALARIES(
	EMP_NO INT,
	SALARY INT,
	FROM_DATE DATE,
	TO_DATE DATE
);